server:
  port: 1002

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tejas
    username: postgres
    password: 2810
    driverClassName: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: 2810
    driverClassName: org.postgresql.Driver

---

spring.profiles.active: local